Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -16,8 +16,10 @@ phases:
       # - sudo ./aws/install
       - aws --version
       - wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
-      - unzip -o terraform_1.0.7_linux_amd64.zip
-      - sudo mv terraform /usr/local/bin/
+      - if ! unzip -o terraform_1.0.7_linux_amd64.zip -d /usr/local/bin/; then
+          echo "Failed to unzip terraform_1.0.7_linux_amd64.zip"
+          exit 1
+        fi
       - terraform --version
   pre_build:
     commands:
